@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< Updated upstream
<<<<<<< Updated upstream
REM Generated by Vivado on Thu Aug 11 02:27:48 -0600 2022
=======
REM Generated by Vivado on Thu Aug 11 08:26:54 -0600 2022
>>>>>>> Stashed changes
=======
REM Generated by Vivado on Thu Aug 11 08:26:54 -0600 2022
>>>>>>> Stashed changes
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< Updated upstream
<<<<<<< Updated upstream
echo "xvlog --incr --relax -prj tb_module_rca_8bits_vlog.prj"
call xvlog  --incr --relax -prj tb_module_rca_8bits_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj tb_module_alu_sumador_vlog.prj"
call xvlog  --incr --relax -prj tb_module_alu_sumador_vlog.prj -log xvlog.log
>>>>>>> Stashed changes
=======
echo "xvlog --incr --relax -prj tb_module_alu_sumador_vlog.prj"
call xvlog  --incr --relax -prj tb_module_alu_sumador_vlog.prj -log xvlog.log
>>>>>>> Stashed changes
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
