@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Thu Aug 11 02:27:50 -0600 2022
=======
REM Generated by Vivado on Thu Aug 11 08:26:58 -0600 2022
>>>>>>> Stashed changes
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< Updated upstream
echo "xelab -wto e15f3d46b1f3470bb6282b72e3ea7fd8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_module_rca_8bits_behav xil_defaultlib.tb_module_rca_8bits xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto e15f3d46b1f3470bb6282b72e3ea7fd8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_module_rca_8bits_behav xil_defaultlib.tb_module_rca_8bits xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto e15f3d46b1f3470bb6282b72e3ea7fd8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_module_alu_sumador_behav xil_defaultlib.tb_module_alu_sumador xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto e15f3d46b1f3470bb6282b72e3ea7fd8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_module_alu_sumador_behav xil_defaultlib.tb_module_alu_sumador xil_defaultlib.glbl -log elaborate.log
>>>>>>> Stashed changes
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
